#!/usr/bin/env python3
"""Genera Grupos A+B+C: 17 spokes (2 comerciales + 9 verticales + 6 capacidades)."""
import os, re
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _make_spoke import SRC, ALT_TEMPLATES, INTERNAL_LINKS_TMPL, transform

ROOT = "/Users/olgagovela/Library/CloudStorage/GoogleDrive-govelamaster@gmail.com/My Drive/Proyectos/gradas-deportivas-futbol"

SPOKES = [
    # ===================== GRUPO A — COMERCIALES =====================
    {
        "slug": "fabricante-gradas-deportivas-mexico",
        "title": "Fabricante de Gradas Deportivas en México | Fábrica Sportmaster",
        "desc": "Sportmaster: fabricante mexicano de gradas deportivas con planta en Monterrey. 12 modelos, acero estructural, INIFED. Envío a 32 estados. Cotiza por WhatsApp en 1 a 2 horas.",
        "kw": "fabricante gradas deportivas, fabricante gradas mexico, fabrica gradas metalicas, fabricante tribunas mexico, fabricante gradas para canchas, planta gradas monterrey, productor gradas deportivas, gradas hechas en mexico",
        "og_t": "Fabricante de Gradas Deportivas en México · Sportmaster",
        "og_d": "Fábrica mexicana de gradas deportivas. Planta en Monterrey. 12 modelos. INIFED. Envío a 32 estados.",
        "tw_t": "Fabricante de Gradas Deportivas en México | Sportmaster",
        "tw_d": "Fábrica directa de gradas deportivas en México. 12 modelos. INIFED. Cotiza por WhatsApp.",
        "bread": "Fabricante de Gradas Deportivas en México",
        "eyebrow": "Planta Monterrey · Envío a 32 estados · Fábrica directa",
        "h1_pre": "Fabricante de<br>gradas deportivas<br>en ",
        "h1_acento": "México",
        "h1_post": ".",
        "sub": "Sportmaster es un fabricante mexicano de gradas deportivas con planta de producción en Monterrey. 12 modelos en <strong>acero estructural</strong> con tratamiento anticorrosivo, soldaduras certificadas, modelos INIFED y opciones modulares.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Soy%20comprador%20y%20quiero%20cotizar%20con%20la%20fabrica%20Sportmaster%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Fábrica directa",
        "bestsellers_h2": "Los 3 modelos más vendidos por nuestra fábrica",
        "beneficios_h2": "Fábrica mexicana con planta en Monterrey. Sin intermediarios.",
        "faq_h2": "Preguntas frecuentes · Fabricante de gradas deportivas",
        "faq1_q": "¿Dónde está la fábrica Sportmaster de gradas deportivas?",
        "faq1_a": "Nuestra planta de fabricación está ubicada en el área metropolitana de <strong>Monterrey, Nuevo León</strong>. Desde ahí fabricamos los 12 modelos del catálogo y enviamos a los 32 estados de la República Mexicana. Atendemos directamente a compradores finales (escuelas, clubes, municipios, hoteles, particulares) sin distribuidores ni intermediarios.",
        "alt_kw": "Fabricante gradas deportivas México",
    },
    {
        "slug": "cotizacion-gradas-deportivas",
        "title": "Cotización de Gradas Deportivas en México | 1 a 2 hrs | Sportmaster",
        "desc": "Cotización formal de gradas deportivas en 1 a 2 horas por WhatsApp. 12 modelos con precio + IVA, ficha técnica PDF, tiempo de entrega y flete por estado. Cotiza ahora.",
        "kw": "cotizacion gradas metalicas, cotizar gradas deportivas, cotizacion gradas para canchas, cotizacion gradas escolares, presupuesto gradas, cuanto cuesta gradas, cotizar gradas inifed, cotizar gradas mexico",
        "og_t": "Cotización de Gradas Deportivas · 1 a 2 horas | Sportmaster",
        "og_d": "Cotización formal en 1 a 2 horas por WhatsApp. 12 modelos + ficha técnica PDF + tiempo de entrega + flete.",
        "tw_t": "Cotización Gradas Deportivas · 1 a 2 hrs | Sportmaster",
        "tw_d": "Cotización formal en menos de 2 horas. 12 modelos. Cotiza por WhatsApp.",
        "bread": "Cotización de Gradas Deportivas",
        "eyebrow": "Respuesta en 1 a 2 hrs · Ficha PDF · Flete",
        "h1_pre": "Cotización de<br>gradas deportivas<br>en ",
        "h1_acento": "1 a 2 horas",
        "h1_post": ".",
        "sub": "Pide tu cotización formal por WhatsApp y recíbela en <strong>1 a 2 horas</strong> con: precio + IVA por modelo, ficha técnica PDF, tiempo de fabricación y flete estimado a tu ciudad.<br><br>Sin compromiso, sin intermediarios.",
        "wa_msg": "Hola!%20Quiero%20cotizacion%20formal%20de%20gradas%20deportivas%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Más cotizados",
        "bestsellers_h2": "Los 3 modelos más cotizados los últimos 12 meses",
        "beneficios_h2": "Cotización formal en 1 a 2 horas. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Cotización de gradas",
        "faq1_q": "¿Qué datos necesito para pedir una cotización formal de gradas?",
        "faq1_a": "Para responderte en <strong>1 a 2 horas</strong> con cotización formal necesitamos: <strong>(1)</strong> capacidad estimada de personas, <strong>(2)</strong> tipo de techo deseado (lona, policarbonato o lámina galvanizada), <strong>(3)</strong> ciudad de instalación (para cotizar flete), <strong>(4)</strong> uso previsto (escuela, club, municipio, hotel, particular) y <strong>(5)</strong> fecha estimada de instalación. Si tienes dudas con alguno de estos puntos, escríbenos y te asesoramos para definirlos.",
        "alt_kw": "Cotización gradas deportivas",
    },
    # ===================== GRUPO B — VERTICALES =====================
    {
        "slug": "gradas-para-cancha-de-futbol-7",
        "title": "Gradas para Cancha de Fútbol 7 en México | Sportmaster",
        "desc": "Gradas para cancha de fútbol 7: 6 modelos de 35 a 150 personas, techo de lona o policarbonato. Acero estructural. Ideal ligas, clubes y municipios. Cotiza por WhatsApp.",
        "kw": "gradas para cancha de futbol 7, gradas futbol 7, gradas para futbol rapido, gradas para canchas futbol 7, gradas liga municipal futbol 7, gradas para club de futbol 7, tribunas para cancha de futbol 7",
        "og_t": "Gradas para Cancha de Fútbol 7 en México · Sportmaster",
        "og_d": "Gradas para fútbol 7: 35 a 150 personas, techo de lona o policarbonato. Ideal para ligas y clubes.",
        "tw_t": "Gradas para Cancha de Fútbol 7 | Sportmaster",
        "tw_d": "Gradas para fútbol 7: 35 a 150p. Cotiza por WhatsApp.",
        "bread": "Gradas para Cancha de Fútbol 7",
        "eyebrow": "Ligas · clubes · municipios · 35 a 150 personas",
        "h1_pre": "Gradas para<br>cancha de<br>",
        "h1_acento": "fútbol 7",
        "h1_post": ".",
        "sub": "6 modelos de gradas para canchas de fútbol 7: capacidad <strong>35 a 150 personas</strong>, techo curvo de lona o policarbonato. Ideales para <strong>ligas, clubes y centros deportivos municipales</strong>.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Quiero%20cotizar%20gradas%20para%20cancha%20de%20futbol%207%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Top fútbol 7",
        "bestsellers_h2": "Los 3 modelos más usados en canchas de fútbol 7",
        "beneficios_h2": "Gradas pensadas para canchas de fútbol 7. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para fútbol 7",
        "faq1_q": "¿Qué capacidad de grada conviene para una cancha de fútbol 7?",
        "faq1_a": "Depende del tipo de uso. Para una <strong>liga amateur o cancha familiar</strong>, recomendamos 35 a 50 personas. Para un <strong>club semi-profesional o escuela</strong>, 75 a 100 personas es lo más común. Para un <strong>centro deportivo municipal o estadio de fútbol 7 con eventos</strong>, recomendamos 150 personas. Si dudas, lo más común en canchas de fútbol 7 son los modelos de 75 a 100 personas en par (uno por lateral).",
        "alt_kw": "Gradas para cancha de fútbol 7",
    },
    {
        "slug": "gradas-para-cancha-de-padel",
        "title": "Gradas para Cancha de Pádel en México | Sportmaster",
        "desc": "Gradas para cancha de pádel: modelos Flex 35p y móviles 12p, ideales para clubes, hoteles y centros de pádel. Techo de lona o policarbonato. Cotiza por WhatsApp.",
        "kw": "gradas para cancha de padel, gradas para padel, gradas para club de padel, gradas para cancha padel, tribunas para padel, gradas padel mexico, gradas para padel center, gradas para tournament padel",
        "og_t": "Gradas para Cancha de Pádel · Clubes y Hoteles | Sportmaster",
        "og_d": "Gradas para pádel: modelos Flex y móviles. Ideales para clubes, hoteles y centros de pádel.",
        "tw_t": "Gradas para Cancha de Pádel | Sportmaster",
        "tw_d": "Gradas Flex y móviles para canchas de pádel. Cotiza por WhatsApp.",
        "bread": "Gradas para Cancha de Pádel",
        "eyebrow": "Pádel · clubes · hoteles · móviles",
        "h1_pre": "Gradas para<br>cancha de<br>",
        "h1_acento": "pádel",
        "h1_post": ".",
        "sub": "Modelos pensados para canchas de pádel: <strong>Grada Flex 35 personas</strong> con techo de lona o policarbonato y <strong>Gradas Móviles 12 asientos con ruedas</strong> para clubes, hoteles y centros de pádel.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Quiero%20cotizar%20gradas%20para%20cancha%20de%20padel%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Top pádel",
        "bestsellers_h2": "Los 3 modelos más usados en clubes de pádel",
        "beneficios_h2": "Gradas que caben en cualquier club de pádel. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para pádel",
        "faq1_q": "¿Qué tipo de grada conviene para una cancha de pádel?",
        "faq1_a": "Para una cancha de pádel estándar (10m × 20m), las opciones más usadas son: <strong>Grada Flex 35 personas</strong> con techo de lona ($78,000) o policarbonato ($88,000) — instalación lateral, perfil bajo para no obstruir la vista; o <strong>Gradas Móviles 12 asientos con ruedas</strong> ($49,500) — sin instalación fija, se reubican entre canchas. Para clubes con torneos o múltiples canchas, recomendamos combinar Flex (laterales fijos) + móviles (espectadores adicionales).",
        "alt_kw": "Gradas para cancha de pádel",
    },
    {
        "slug": "gradas-para-cancha-de-beisbol",
        "title": "Gradas para Cancha de Béisbol en México | Sportmaster",
        "desc": "Gradas para campo de béisbol: 6 modelos de 50 a 150 personas, techo de lona o policarbonato. Acero estructural para uso intensivo. Cotiza por WhatsApp.",
        "kw": "gradas para cancha de beisbol, gradas para beisbol, gradas para campo de beisbol, tribunas para beisbol, gradas estadio beisbol, gradas para liga de beisbol, gradas escolares beisbol",
        "og_t": "Gradas para Cancha de Béisbol · 50 a 150 personas | Sportmaster",
        "og_d": "Gradas para campo de béisbol: capacidad 50 a 150 personas, techo de lona o policarbonato.",
        "tw_t": "Gradas para Cancha de Béisbol | Sportmaster",
        "tw_d": "Gradas para béisbol 50 a 150 personas. Cotiza por WhatsApp.",
        "bread": "Gradas para Cancha de Béisbol",
        "eyebrow": "Béisbol · ligas · escuelas · 50 a 150 personas",
        "h1_pre": "Gradas para<br>cancha de<br>",
        "h1_acento": "béisbol",
        "h1_post": ".",
        "sub": "Gradas para campo de béisbol: <strong>6 modelos de 50 a 150 personas</strong> con techo de lona o policarbonato. Ideales para campos escolares, ligas municipales y clubes de béisbol amateur.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Quiero%20cotizar%20gradas%20para%20cancha%20de%20beisbol%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Top béisbol",
        "bestsellers_h2": "Los 3 modelos más usados en campos de béisbol",
        "beneficios_h2": "Gradas que aguantan partidos de 3 horas. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para béisbol",
        "faq1_q": "¿Qué capacidad de grada se necesita para un campo de béisbol?",
        "faq1_a": "Para un <strong>campo escolar de béisbol</strong>, 50 personas es lo común (modelo INIFED de 50p o Grada 50p Techo Curvo Lona). Para una <strong>liga municipal</strong>, 75 a 100 personas según afluencia. Para un <strong>club de béisbol amateur con público regular</strong>, 150 personas distribuidas detrás de home y por lateral. La mayoría de campos usan 1 grada detrás de home + bancas a nivel de campo en lateral.",
        "alt_kw": "Gradas para cancha de béisbol",
    },
    {
        "slug": "gradas-para-cancha-de-futbol-americano",
        "title": "Gradas para Cancha de Fútbol Americano | Sportmaster México",
        "desc": "Gradas para cancha de fútbol americano: modelos de 100 y 150 personas, ideales para colegios, prepas y ligas. Acero estructural con techo. Cotiza por WhatsApp.",
        "kw": "gradas para futbol americano, gradas para tochito, gradas para canchas tochito, gradas para futbol bandera, tribunas para futbol americano, gradas para liga colegial, gradas para prepa americano",
        "og_t": "Gradas para Cancha de Fútbol Americano · Colegios y Ligas",
        "og_d": "Gradas para fútbol americano y tochito: 100 a 150 personas. Ideal colegios y prepas.",
        "tw_t": "Gradas para Fútbol Americano y Tochito | Sportmaster",
        "tw_d": "Gradas para fútbol americano 100 a 150p. Cotiza por WhatsApp.",
        "bread": "Gradas para Cancha de Fútbol Americano",
        "eyebrow": "Fútbol americano · tochito · colegios · ligas",
        "h1_pre": "Gradas para<br>cancha de fútbol<br>",
        "h1_acento": "americano",
        "h1_post": ".",
        "sub": "Gradas para canchas de fútbol americano, tochito y fútbol bandera: <strong>modelos de 100 y 150 personas</strong>, ideales para colegios, prepas, universidades y ligas amateur.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Quiero%20cotizar%20gradas%20para%20cancha%20de%20futbol%20americano%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Top fútbol americano",
        "bestsellers_h2": "Los 3 modelos más usados en canchas de fútbol americano",
        "beneficios_h2": "Gradas para el deporte que mueve a las prepas. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para fútbol americano",
        "faq1_q": "¿Qué capacidad de grada se necesita para una cancha de fútbol americano?",
        "faq1_a": "Para una <strong>prepa o colegio con equipo de fútbol americano</strong>, recomendamos modelos de 100 personas (Grada 100p Techo Recto Lona) o 150 personas (Grada 150p Techo Curvo Lona) en par, uno por lateral. Para una <strong>liga colegial o universitaria</strong> con asistencia regular, lo común es 2 gradas de 150p (300 espectadores totales). Para fútbol bandera y tochito en canchas más pequeñas, modelos de 75 a 100 personas suelen ser suficientes.",
        "alt_kw": "Gradas para cancha de fútbol americano",
    },
    {
        "slug": "gradas-para-eventos",
        "title": "Gradas para Eventos en México · Móviles y Modulares | Sportmaster",
        "desc": "Gradas para eventos en México: gradas móviles con ruedas y modulares Flex 35p. Reubicables, fáciles de transportar. Ideales para torneos, ferias y eventos itinerantes. Cotiza ahora.",
        "kw": "gradas para eventos, gradas para eventos precio, gradas moviles eventos, gradas para torneos, gradas para ferias, gradas para festivales, gradas itinerantes, alquiler gradas eventos, gradas desmontables eventos",
        "og_t": "Gradas para Eventos · Móviles y Modulares | Sportmaster",
        "og_d": "Gradas para eventos itinerantes: móviles con ruedas + modulares Flex. Reubicables.",
        "tw_t": "Gradas para Eventos · Móviles y Modulares | Sportmaster",
        "tw_d": "Gradas móviles y modulares para eventos. Reubicables. Cotiza por WhatsApp.",
        "bread": "Gradas para Eventos",
        "eyebrow": "Móviles · modulares · eventos itinerantes",
        "h1_pre": "Gradas para<br>",
        "h1_acento": "eventos",
        "h1_post": "<br>móviles.",
        "sub": "Para eventos itinerantes, torneos y ferias ofrecemos <strong>Gradas Móviles 12 asientos con ruedas</strong> ($49,500) y <strong>Grada Flex 35 personas</strong> con techo modular. Se transportan, instalan y desmontan en horas.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Quiero%20cotizar%20gradas%20para%20un%20evento%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Top eventos",
        "bestsellers_h2": "Los 3 modelos más usados en eventos",
        "beneficios_h2": "Gradas que llegan, sientan público y se van. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para eventos",
        "faq1_q": "¿Qué gradas conviene para un evento itinerante o de pocos días?",
        "faq1_a": "Para eventos itinerantes (torneos, ferias, festivales, eventos corporativos), los modelos ideales son: <strong>Gradas Móviles 12 asientos con ruedas</strong> ($49,500) — se transportan en camioneta o flete pequeño y se reubican en minutos; o <strong>Grada Flex 35 personas con techo de lona</strong> ($78,000) — se desarman y arman en horas. Si solo necesitas gradas para 1-3 días específicos, también te asesoramos sobre opciones de renta a través de aliados.",
        "alt_kw": "Gradas para eventos",
    },
    {
        "slug": "gradas-para-escuela-publica-leen",
        "title": "Gradas para Escuela Pública con LEEN | INIFED | Sportmaster",
        "desc": "Gradas INIFED para escuela pública: cubre el costo con La Escuela Es Nuestra (LEEN), CEAP o FAEB. Modelo 50p policarbonato INIFED. Cotiza por WhatsApp.",
        "kw": "gradas para escuela publica, gradas con LEEN, gradas con La Escuela Es Nuestra, gradas con CEAP, gradas con FAEB, gradas INIFED escuela publica, gradas escolares publicas, gradas primaria publica, gradas secundaria publica",
        "og_t": "Gradas para Escuela Pública · LEEN / CEAP / FAEB | INIFED",
        "og_d": "Gradas INIFED financiables con LEEN, CEAP o FAEB. Modelo 50p policarbonato homologado.",
        "tw_t": "Gradas para Escuela Pública con LEEN | Sportmaster",
        "tw_d": "Gradas INIFED para escuela pública. LEEN / CEAP / FAEB.",
        "bread": "Gradas para Escuela Pública con LEEN",
        "eyebrow": "LEEN · CEAP · FAEB · INIFED",
        "h1_pre": "Gradas para<br>escuela pública<br>con ",
        "h1_acento": "LEEN",
        "h1_post": ".",
        "sub": "El modelo <strong>Grada 50 Personas Policarbonato INIFED</strong> es el único homologado para canchas escolares públicas. Puede adquirirse con el recurso federal de <strong>La Escuela Es Nuestra (LEEN), CEAP o FAEB</strong>.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Soy%20de%20escuela%20publica%20y%20quiero%20gradas%20con%20LEEN%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Top escuelas públicas",
        "bestsellers_h2": "El modelo INIFED + 2 alternativas para escuela pública",
        "beneficios_h2": "Gradas INIFED para tu escuela pública. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para escuela pública con LEEN",
        "faq1_q": "¿Cómo se compran gradas con el programa La Escuela Es Nuestra (LEEN)?",
        "faq1_a": "El proceso es: <strong>(1)</strong> El comité escolar de tu plantel registra el proyecto de mejora con gradas en la plataforma LEEN. <strong>(2)</strong> Una vez aprobado el recurso, nos contactan por WhatsApp para cotizar el modelo Grada 50 Personas Policarbonato INIFED ($105,000). <strong>(3)</strong> Entregamos factura a nombre del comité escolar para que ejerzan el recurso. <strong>(4)</strong> Fabricamos en 4 a 6 semanas y entregamos en sitio. CEAP y FAEB funcionan de manera similar pero a través de la SEP estatal o federal según corresponda.",
        "alt_kw": "Gradas para escuela pública con LEEN INIFED",
    },
    {
        "slug": "gradas-para-escuela-privada-colegio",
        "title": "Gradas para Escuela Privada y Colegio | Sportmaster México",
        "desc": "Gradas para colegio privado, escuela privada y prepa: 12 modelos en acero estructural con techo. INIFED disponible. Cotiza por WhatsApp.",
        "kw": "gradas para escuela privada, gradas para colegio, gradas para colegio privado, gradas para prepa privada, gradas para universidad, gradas para institucion educativa, gradas escolares privadas",
        "og_t": "Gradas para Escuela Privada y Colegio | Sportmaster México",
        "og_d": "Gradas para colegios y escuelas privadas: 12 modelos. Acero estructural. INIFED disponible.",
        "tw_t": "Gradas para Escuela Privada y Colegio | Sportmaster",
        "tw_d": "Gradas para colegios privados y prepas. 12 modelos. Cotiza por WhatsApp.",
        "bread": "Gradas para Escuela Privada y Colegio",
        "eyebrow": "Colegios · prepas · universidades · 12 modelos",
        "h1_pre": "Gradas para<br>",
        "h1_acento": "escuela privada",
        "h1_post": "<br>y colegio.",
        "sub": "Para colegios privados, prepas y universidades ofrecemos los 12 modelos del catálogo: <strong>desde Flex 35 personas hasta gradas de 150 personas</strong>, techo de lona, policarbonato o lámina galvanizada.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Soy%20de%20colegio%20privado%20y%20quiero%20cotizar%20gradas%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Top colegios privados",
        "bestsellers_h2": "Los 3 modelos más usados en colegios privados",
        "beneficios_h2": "Gradas con el nivel que tu colegio exige. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para escuela privada y colegio",
        "faq1_q": "¿Qué modelo de grada se recomienda para un colegio privado?",
        "faq1_a": "Depende del tipo de cancha y nivel del colegio. Para <strong>primarias y secundarias privadas</strong>, los modelos de 35 a 50 personas con techo de lona o policarbonato son los más comunes. Para <strong>prepas con equipos deportivos activos</strong>, recomendamos 75 a 100 personas en par. Para <strong>universidades o colegios con estadio propio</strong>, modelos de 150 personas. Los colegios privados no requieren homologación INIFED (esa es para escuela pública), por lo que pueden elegir cualquiera de los 12 modelos según presupuesto y estética del campus.",
        "alt_kw": "Gradas para escuela privada y colegio",
    },
    {
        "slug": "gradas-para-municipio-cancha-publica",
        "title": "Gradas para Municipio y Cancha Pública | Sportmaster México",
        "desc": "Gradas para municipios y canchas públicas: 12 modelos en acero estructural con tratamiento anticorrosivo. Envío e instalación a 32 estados. Cotiza por WhatsApp.",
        "kw": "gradas para municipio, gradas para cancha publica, gradas para unidad deportiva, gradas para alcaldia, gradas para municipio precio, gradas para cancha municipal, gradas para parque publico, tribunas para municipio",
        "og_t": "Gradas para Municipio y Cancha Pública | Sportmaster México",
        "og_d": "Gradas para municipios: 12 modelos para canchas públicas, unidades deportivas y parques.",
        "tw_t": "Gradas para Municipio y Cancha Pública | Sportmaster",
        "tw_d": "Gradas para canchas públicas municipales. 12 modelos. Cotiza por WhatsApp.",
        "bread": "Gradas para Municipio y Cancha Pública",
        "eyebrow": "Municipios · unidades deportivas · 32 estados",
        "h1_pre": "Gradas para<br>",
        "h1_acento": "municipio",
        "h1_post": "<br>y cancha pública.",
        "sub": "Gradas para canchas públicas, unidades deportivas y parques municipales: <strong>12 modelos</strong> en acero estructural con tratamiento anticorrosivo para uso intensivo en exterior.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Soy%20de%20municipio%20y%20quiero%20cotizar%20gradas%20para%20cancha%20publica%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Top municipios",
        "bestsellers_h2": "Los 3 modelos más usados por municipios",
        "beneficios_h2": "Gradas que tu municipio puede licitar con confianza. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para municipio y cancha pública",
        "faq1_q": "¿Cómo se compran gradas para una cancha pública o unidad deportiva municipal?",
        "faq1_a": "El proceso depende del monto y el procedimiento administrativo del municipio. Para montos menores se puede comprar por adjudicación directa o invitación a 3. Para montos mayores suele requerirse licitación pública. Nosotros podemos: <strong>(1)</strong> cotizar formalmente con factura y ficha técnica para tu expediente, <strong>(2)</strong> participar en licitación con la documentación requerida (constancia fiscal, opinión de cumplimiento SAT, comprobante de domicilio, etc.) y <strong>(3)</strong> coordinar entrega e instalación en la cancha pública. Escríbenos con tu requerimiento y te apoyamos con el proceso.",
        "alt_kw": "Gradas para municipio y cancha pública",
    },
    {
        "slug": "gradas-para-club-deportivo-hotel",
        "title": "Gradas para Club Deportivo y Hotel | Sportmaster México",
        "desc": "Gradas para club deportivo, hotel y resort: 12 modelos con techo, acero estructural. Acabados premium. Acentos y colores a elegir. Cotiza por WhatsApp.",
        "kw": "gradas para club deportivo, gradas para hotel, gradas para resort, gradas para club, gradas para hotel todo incluido, gradas para hacienda, gradas para campo deportivo hotel, gradas para club social",
        "og_t": "Gradas para Club Deportivo y Hotel | Sportmaster México",
        "og_d": "Gradas para clubes deportivos y hoteles: 12 modelos con techo, acero estructural premium.",
        "tw_t": "Gradas para Club Deportivo y Hotel | Sportmaster",
        "tw_d": "Gradas premium para clubes y hoteles. 12 modelos. Cotiza por WhatsApp.",
        "bread": "Gradas para Club Deportivo y Hotel",
        "eyebrow": "Clubes · hoteles · resorts · acabados premium",
        "h1_pre": "Gradas para<br>club deportivo<br>y ",
        "h1_acento": "hotel",
        "h1_post": ".",
        "sub": "Para clubes deportivos, hoteles y resorts con canchas: 12 modelos con techo, acero estructural y acabados de alta calidad. <strong>Color de lona y pintura de estructura a elegir</strong> para integrarse al diseño del club.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Soy%20de%20un%20club%20u%20hotel%20y%20quiero%20cotizar%20gradas%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Top clubes y hoteles",
        "bestsellers_h2": "Los 3 modelos más usados en clubes y hoteles",
        "beneficios_h2": "Gradas con el acabado que tu club merece. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para club y hotel",
        "faq1_q": "¿Pueden personalizar el color o acabado de las gradas para mi club u hotel?",
        "faq1_a": "Sí. Para clubes deportivos, hoteles y resorts ofrecemos personalización en: <strong>(1)</strong> color de lona del techo (paleta de colores estándar de proveedor; podemos cotizar lona pantone específica para tu marca), <strong>(2)</strong> color de pintura de la estructura de acero (gama estándar o color personalizado con sobrecosto) y <strong>(3)</strong> placa con tu logo en el frente de la grada. La estructura y dimensiones son las del modelo elegido; los acabados se confirman antes de fabricación.",
        "alt_kw": "Gradas para club deportivo y hotel",
    },
    # ===================== GRUPO C — CAPACIDADES =====================
    {
        "slug": "gradas-para-35-personas",
        "title": "Gradas para 35 Personas · Techo Curvo Lona o Policarbonato | Sportmaster",
        "desc": "Gradas para 35 personas: 2 modelos con techo curvo (lona desde $78,000 o policarbonato desde $88,000). Ideal canchas pequeñas, clubes amateur. Cotiza por WhatsApp.",
        "kw": "gradas para 35 personas, gradas 35 personas, grada 35 personas precio, gradas 35 personas lona, gradas 35 personas policarbonato, gradas pequeñas techo, grada chica para cancha",
        "og_t": "Gradas para 35 Personas · Desde $78,000 + IVA | Sportmaster",
        "og_d": "Gradas para 35 personas con techo curvo de lona o policarbonato. Ideal canchas pequeñas.",
        "tw_t": "Gradas para 35 Personas con Techo | Sportmaster",
        "tw_d": "Gradas 35 personas desde $78,000. Lona o policarbonato.",
        "bread": "Gradas para 35 Personas",
        "eyebrow": "35 personas · lona o policarbonato · techo curvo",
        "h1_pre": "Gradas para<br>",
        "h1_acento": "35 personas",
        "h1_post": ".",
        "sub": "2 modelos con techo curvo: <strong>Grada 35p Techo Curvo Lona</strong> desde $78,000 + IVA y <strong>Grada 35p Techo Curvo Policarbonato</strong> desde $88,000 + IVA. Ideal para canchas pequeñas, clubes amateur y escuelas con espacio reducido.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Quiero%20cotizar%20una%20grada%20de%2035%20personas%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Modelos 35p",
        "bestsellers_h2": "Las 3 opciones para 35 personas (incluyendo Flex modular)",
        "beneficios_h2": "Gradas de 35 personas con techo. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para 35 personas",
        "faq1_q": "¿Cuáles son las medidas y precio de una grada de 35 personas?",
        "faq1_a": "Una grada de 35 personas Sportmaster mide <strong>6 m de largo, 2 m de fondo y 3.50 m de altura</strong> con techo curvo. Precios: con <strong>lona desde $78,000 + IVA</strong>, con <strong>policarbonato desde $88,000 + IVA</strong>. También disponemos del modelo Flex 35 personas con misma capacidad pero estructura desmontable, ideal para pádel y eventos.",
        "alt_kw": "Gradas para 35 personas",
    },
    {
        "slug": "gradas-para-50-personas",
        "title": "Gradas para 50 Personas INIFED · Desde $99,500 | Sportmaster",
        "desc": "Gradas para 50 personas: 2 modelos con techo curvo (lona $99,500 o policarbonato INIFED $105,000). El modelo INIFED es el único para escuelas públicas. Cotiza por WhatsApp.",
        "kw": "gradas para 50 personas, gradas 50 personas, gradas 50 personas inifed, grada 50 personas precio, gradas 50 personas policarbonato, gradas 50 personas lona, gradas escolares 50 personas",
        "og_t": "Gradas para 50 Personas · INIFED Disponible | Sportmaster",
        "og_d": "Gradas 50 personas con techo. INIFED disponible. Desde $99,500 + IVA.",
        "tw_t": "Gradas para 50 Personas con Techo INIFED | Sportmaster",
        "tw_d": "Gradas 50p con techo. INIFED. Desde $99,500 + IVA.",
        "bread": "Gradas para 50 Personas",
        "eyebrow": "50 personas · INIFED · lona o policarbonato",
        "h1_pre": "Gradas para<br>",
        "h1_acento": "50 personas",
        "h1_post": ".",
        "sub": "2 modelos disponibles: <strong>Grada 50p Techo Curvo Lona</strong> ($99,500 + IVA) y <strong>Grada 50p Techo Curvo Policarbonato INIFED</strong> ($105,000 + IVA). El modelo INIFED es el único homologado para canchas escolares públicas.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Quiero%20cotizar%20una%20grada%20de%2050%20personas%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Modelos 50p",
        "bestsellers_h2": "Las 3 opciones para 50 personas (con y sin INIFED)",
        "beneficios_h2": "Gradas de 50 personas. La capacidad más vendida.",
        "faq_h2": "Preguntas frecuentes · Gradas para 50 personas",
        "faq1_q": "¿Qué diferencia hay entre la grada de 50 personas con lona y la INIFED de policarbonato?",
        "faq1_a": "Ambas tienen las mismas dimensiones (<strong>10 m × 3.50 m × 1.50 m de fondo</strong>) y misma capacidad (50 personas sentadas). Las diferencias son: <strong>(1) Techo</strong> — la de lona usa vinilo reforzado ($99,500), la INIFED usa policarbonato compacto 6mm traslúcido ($105,000). <strong>(2) Normativa</strong> — solo la de policarbonato cumple lineamientos INIFED y es la única elegible para canchas escolares públicas con LEEN, CEAP o FAEB. <strong>(3) Granizo y luz</strong> — el policarbonato resiste granizo y deja pasar luz natural; la lona no.",
        "alt_kw": "Gradas para 50 personas INIFED",
    },
    {
        "slug": "gradas-para-75-personas",
        "title": "Gradas para 75 Personas · Desde $118,000 + IVA | Sportmaster",
        "desc": "Gradas para 75 personas: 2 modelos con techo curvo (lona $118,000 o policarbonato $135,000). Ideal clubes semi-profesionales y canchas medianas. Cotiza por WhatsApp.",
        "kw": "gradas para 75 personas, gradas 75 personas, grada 75 personas precio, gradas 75 personas lona, gradas 75 personas policarbonato, gradas para club semipro, gradas medianas con techo",
        "og_t": "Gradas para 75 Personas · Desde $118,000 + IVA | Sportmaster",
        "og_d": "Gradas 75 personas con techo de lona o policarbonato. Ideal clubes semi-profesionales.",
        "tw_t": "Gradas para 75 Personas con Techo | Sportmaster",
        "tw_d": "Gradas 75p con techo desde $118,000 + IVA.",
        "bread": "Gradas para 75 Personas",
        "eyebrow": "75 personas · lona o policarbonato · clubes",
        "h1_pre": "Gradas para<br>",
        "h1_acento": "75 personas",
        "h1_post": ".",
        "sub": "2 modelos con techo curvo: <strong>Grada 75p Techo Curvo Lona</strong> ($118,000 + IVA) y <strong>Grada 75p Techo Curvo Policarbonato</strong> ($135,000 + IVA). La capacidad más vendida para clubes semi-profesionales y canchas con afluencia regular.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Quiero%20cotizar%20una%20grada%20de%2075%20personas%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Modelos 75p",
        "bestsellers_h2": "Los 2 modelos disponibles para 75 personas",
        "beneficios_h2": "Gradas de 75 personas para clubes semi-pro. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para 75 personas",
        "faq1_q": "¿Qué uso recomienda Sportmaster para la grada de 75 personas?",
        "faq1_a": "La grada de 75 personas es la <strong>capacidad más vendida para clubes semi-profesionales y canchas de fútbol 7 con afluencia regular</strong>. Sus dimensiones (<strong>10 m × 3.50 m × 2 m de fondo</strong>) la hacen ideal para: clubes deportivos con equipo amateur o juvenil, canchas escolares de prepa o universidad, ligas municipales, escuelas privadas con eventos deportivos regulares. Si tu cancha es de fútbol 7 o pádel y esperas 50 a 100 espectadores en promedio, este es el modelo correcto.",
        "alt_kw": "Gradas para 75 personas",
    },
    {
        "slug": "gradas-para-100-personas",
        "title": "Gradas para 100 Personas · Desde $138,000 + IVA | Sportmaster",
        "desc": "Gradas para 100 personas: Grada Techo Recto Lona ($138,000 + IVA). Ideal estadios pequeños, prepas y clubes con afluencia regular. Cotiza por WhatsApp.",
        "kw": "gradas para 100 personas, gradas 100 personas, grada 100 personas precio, gradas 100 personas lona, gradas para estadio pequeño, gradas para liga municipal, gradas para prepa publica",
        "og_t": "Gradas para 100 Personas · Techo Recto Lona | Sportmaster",
        "og_d": "Gradas 100 personas Techo Recto Lona. $138,000 + IVA. Estadios pequeños y prepas.",
        "tw_t": "Gradas para 100 Personas con Techo Recto | Sportmaster",
        "tw_d": "Gradas 100p Techo Recto Lona $138,000 + IVA.",
        "bread": "Gradas para 100 Personas",
        "eyebrow": "100 personas · techo recto lona · estadios pequeños",
        "h1_pre": "Gradas para<br>",
        "h1_acento": "100 personas",
        "h1_post": ".",
        "sub": "<strong>Grada 100 Personas Techo Recto Lona</strong> ($138,000 + IVA): el modelo escalonado en una sola pieza ideal para estadios pequeños, prepas, ligas municipales y clubes con afluencia regular.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Quiero%20cotizar%20una%20grada%20de%20100%20personas%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Modelo 100p",
        "bestsellers_h2": "Grada 100 personas y modelos relacionados",
        "beneficios_h2": "Gradas de 100 personas para estadios pequeños. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para 100 personas",
        "faq1_q": "¿Cuál son las medidas de la grada de 100 personas?",
        "faq1_a": "La <strong>Grada 100 Personas Techo Recto Lona</strong> mide <strong>20 m de largo, 2 m de fondo y 3.50 m de altura</strong>. El techo es recto reforzado (no curvo) para distribuir el peso en piezas largas. Es la opción más usada para estadios escolares de prepa o universidad, ligas municipales con público regular, clubes semiprofesionales de fútbol 7 o americano. Si necesitas 100 personas pero en menos largo, podemos cotizarte 2 gradas de 50p en par.",
        "alt_kw": "Gradas para 100 personas",
    },
    {
        "slug": "gradas-para-150-personas",
        "title": "Gradas para 150 Personas · Desde $245,000 + IVA | Sportmaster",
        "desc": "Gradas para 150 personas: 2 modelos con techo curvo (lona o lámina galvanizada) a $245,000 + IVA. Ideal estadios municipales, clubes con público frecuente. Cotiza por WhatsApp.",
        "kw": "gradas para 150 personas, gradas 150 personas, grada 150 personas precio, gradas 150 personas lona, gradas 150 personas lamina galvanizada, gradas para estadio municipal, gradas grandes con techo, tribunas 150 personas",
        "og_t": "Gradas para 150 Personas · Desde $245,000 + IVA | Sportmaster",
        "og_d": "Gradas 150 personas con techo curvo. Lona o lámina galvanizada. $245,000 + IVA.",
        "tw_t": "Gradas para 150 Personas con Techo | Sportmaster",
        "tw_d": "Gradas 150p con techo curvo desde $245,000 + IVA.",
        "bread": "Gradas para 150 Personas",
        "eyebrow": "150 personas · techo curvo · estadios municipales",
        "h1_pre": "Gradas para<br>",
        "h1_acento": "150 personas",
        "h1_post": ".",
        "sub": "2 modelos con techo curvo de gran luz: <strong>Grada 150p Lona</strong> ($245,000 + IVA) y <strong>Grada 150p Lámina Galvanizada</strong> ($245,000 + IVA). Ideal para estadios municipales, clubes con público frecuente y canchas con eventos regulares.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Quiero%20cotizar%20una%20grada%20de%20150%20personas%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Modelos 150p",
        "bestsellers_h2": "Los modelos disponibles para 150 personas",
        "beneficios_h2": "Gradas de 150 personas para estadios municipales. Sin letra pequeña.",
        "faq_h2": "Preguntas frecuentes · Gradas para 150 personas",
        "faq1_q": "¿Qué diferencia hay entre techo de lona y lámina galvanizada en la grada de 150 personas?",
        "faq1_a": "Ambas tienen las mismas dimensiones (<strong>20 m × 3.50 m</strong>) y capacidad (150 personas). La diferencia es el material del techo: <strong>lona</strong> — vinilo reforzado, más ligero, más fácil de reemplazar, opción más común; <strong>lámina galvanizada</strong> — la opción más resistente para climas extremos, lluvia constante, granizo y zonas costeras con corrosión. Ambos cuestan $245,000 + IVA. Si tu cancha está en costa, sierra húmeda o zona con granizo, te recomendamos lámina galvanizada.",
        "alt_kw": "Gradas para 150 personas",
    },
    {
        "slug": "gradas-para-mas-de-150-personas",
        "title": "Gradas para Más de 150 Personas · Capacidad Personalizada | Sportmaster",
        "desc": "Gradas para más de 150 personas: capacidad personalizada con módulos combinables. Para estadios, universidades y eventos grandes. Cotizamos a la medida por WhatsApp.",
        "kw": "gradas para mas de 150 personas, gradas para 200 personas, gradas grandes, gradas para estadio, gradas para 300 personas, gradas modulares combinables, gradas a la medida, gradas grandes precio",
        "og_t": "Gradas para Más de 150 Personas · Capacidad Personalizada",
        "og_d": "Capacidad mayor a 150 personas con módulos combinables. A la medida por proyecto.",
        "tw_t": "Gradas para Más de 150 Personas | Sportmaster",
        "tw_d": "Capacidad personalizada con módulos combinables. Cotiza por WhatsApp.",
        "bread": "Gradas para Más de 150 Personas",
        "eyebrow": "Capacidad personalizada · módulos combinables",
        "h1_pre": "Gradas para más<br>de ",
        "h1_acento": "150 personas",
        "h1_post": ".",
        "sub": "Para proyectos que requieren más de 150 personas, combinamos módulos de nuestros 12 modelos para llegar a la capacidad necesaria. <strong>200 personas = 2 × Grada 100p</strong>, <strong>300 personas = 2 × Grada 150p</strong>, etc. Cotizamos a la medida según tu proyecto.<br><br>Cotización en 1 a 2 horas por WhatsApp.",
        "wa_msg": "Hola!%20Necesito%20gradas%20para%20mas%20de%20150%20personas%20-%20vengo%20de%20gradasdefutbol.mx",
        "bestsellers_eyebrow": "Combinaciones modulares",
        "bestsellers_h2": "Combinaciones modulares para capacidades grandes",
        "beneficios_h2": "Gradas grandes resueltas con módulos combinables.",
        "faq_h2": "Preguntas frecuentes · Gradas para más de 150 personas",
        "faq1_q": "¿Pueden fabricar una grada de 200 o 300 personas?",
        "faq1_a": "No fabricamos una grada de 200 o 300 personas en una sola pieza. En su lugar, combinamos módulos de nuestros 12 modelos para alcanzar la capacidad requerida. Por ejemplo: <strong>200 personas</strong> = 2 gradas de 100p en par (uno por lateral); <strong>300 personas</strong> = 2 gradas de 150p; <strong>400+ personas</strong> = combinación de 150p + 100p + 50p según la geometría de tu cancha. Esto es más práctico para transporte, instalación y mantenimiento que una sola estructura gigante. Cotizamos la combinación a la medida de tu proyecto.",
        "alt_kw": "Gradas para más de 150 personas",
    },
]

def main():
    src = open(SRC).read()
    for sp in SPOKES:
        out_dir = f"{ROOT}/{sp['slug']}"
        os.makedirs(out_dir, exist_ok=True)
        out = transform(src, sp)
        with open(f"{out_dir}/index.html", "w") as f:
            f.write(out)
        print(f"  ✓ /{sp['slug']}/")
    print(f"\n✓ {len(SPOKES)} spokes generados.")


if __name__ == "__main__":
    main()
